-- =====================================================================
-- MIGRACIÓN 013: Forzar recarga del schema cache de PostgREST
-- =====================================================================
-- La migración 012 (20260623000003) hizo DROP + CREATE de
-- `registrar_eutanasia` cambiando su firma (nuevo parámetro p_user_id).
-- PostgREST cachea el esquema y, en este entorno, NO recargó automáticamente
-- tras el push: quedó la firma vieja (10 args, sin p_user_id) en cache, así que
-- toda llamada al RPC con p_user_id respondía
--   "Could not find the function public.registrar_eutanasia(...) in the schema cache"
-- y el RPC nunca llegaba a ejecutarse (los tests de integración lo detectaron).
--
-- `NOTIFY pgrst, 'reload schema'` es el mecanismo canónico de Supabase para que
-- PostgREST relea el esquema. La notificación se entrega al COMMIT de esta
-- migración (db push), y PostgREST recarga la firma nueva de la función.
--
-- Convención a futuro: las migraciones que agreguen o cambien funciones
-- expuestas por PostgREST (RPC) deberían terminar con este NOTIFY para evitar
-- exactamente este desfasaje de cache.
-- =====================================================================

NOTIFY pgrst, 'reload schema';
